// @ts-check

import { schemaId as id } from './schema-shared.js';

export const BASE_RESEARCH_SCHEMAS = Object.freeze({
  'affine-geometry': {
    $id: 'https://polytwist.dev/schema/affine-geometry.schema.json',
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'PolyTwist canonical affine geometry artifact',
    type: 'object',
    required: [
      'schema',
      'exactness',
      'normalizedInput',
      'body',
      'atomicCells',
      'adjacency',
      'physicalPieces',
      'exposedSurfaces',
      'diagnostics',
      'certificates',
      'hashes',
    ],
    properties: {
      schema: { const: 'polytwist.affine-geometry.v1' },
      exactness: { type: 'object' },
      normalizedInput: { type: 'object' },
      body: { type: 'object' },
      atomicCells: { type: 'array' },
      adjacency: { type: 'array' },
      physicalPieces: { type: 'array' },
      exposedSurfaces: { type: 'array' },
      boundaryTraces: { type: 'array' },
      diagnostics: { type: 'object' },
      certificates: { type: 'object' },
      hashes: {
        type: 'object',
        required: ['input', 'geometry'],
        properties: {
          input: { type: 'string', pattern: '^[0-9a-f]{64}$' },
          geometry: { type: 'string', pattern: '^[0-9a-f]{64}$' },
        },
      },
    },
  },
  'api-envelope': {
    $id: id('api-envelope'),
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'KineScope API envelope',
    type: 'object',
    required: ['ok', 'requestId'],
    properties: {
      ok: { type: 'boolean' },
      requestId: { type: 'string' },
      data: {},
      error: {
        type: 'object',
        required: ['code', 'message'],
        properties: { code: { type: 'string' }, message: { type: 'string' }, details: {} },
      },
    },
  },
  'research-suite': {
    $id: id('research-suite'),
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'KineScope research suite',
    type: 'object',
    required: ['schema', 'suiteId', 'engineVersion', 'configuration', 'summary', 'public', 'private'],
    properties: {
      schema: { const: 'kinescope.research-suite.v1' },
      suiteId: { type: 'string' },
      engineVersion: { type: 'string' },
      configuration: { type: 'object' },
      summary: { type: 'object' },
      public: { type: 'object', required: ['episodes', 'items'] },
      private: { type: 'object', required: ['episodes', 'targets', 'diagnostics'] },
      suiteDigest: { type: 'string' },
    },
  },
  'benchmark-item': {
    $id: id('benchmark-item'),
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'Public benchmark item',
    type: 'object',
    required: ['schema', 'itemId', 'taskId', 'split', 'input', 'metadata'],
    properties: {
      schema: { const: 'kinescope.item-public.v1' },
      itemId: { type: 'string' },
      taskId: { type: 'string' },
      split: { type: 'string' },
      answerType: { type: 'string' },
      input: { type: 'object' },
      metadata: { type: 'object' },
    },
  },
  'private-target': {
    $id: id('private-target'),
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'Evaluator-private target',
    type: 'object',
    required: ['schema', 'itemId', 'taskId', 'target', 'verification'],
    properties: {
      schema: { const: 'kinescope.target-private.v1' },
      itemId: { type: 'string' },
      taskId: { type: 'string' },
      target: {},
      verification: { type: 'object' },
    },
  },
  prediction: {
    $id: id('prediction'),
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'Model prediction',
    type: 'object',
    required: ['itemId', 'answer'],
    properties: {
      itemId: { type: 'string' },
      answer: {},
      confidence: { type: 'number', minimum: 0, maximum: 1 },
      latencyMs: { type: 'number', minimum: 0 },
      inputTokens: { type: 'integer', minimum: 0 },
      outputTokens: { type: 'integer', minimum: 0 },
      costUsd: { type: 'number', minimum: 0 },
      metadata: { type: 'object' },
    },
  },
  evaluation: {
    $id: id('evaluation'),
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'Evaluation report',
    type: 'object',
    required: ['schema', 'suiteId', 'coverage', 'aggregate', 'results'],
    properties: {
      schema: { const: 'kinescope.evaluation.v1' },
      suiteId: { type: 'string' },
      coverage: { type: 'object' },
      aggregate: { type: 'object' },
      results: { type: 'array' },
    },
  },
  'ideal-rigid-display-experiment': {
    $id: 'https://polytwist.dev/schema/ideal-rigid-display-experiment.schema.json',
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'PolyTwist ideal-rigid display closure experiment',
    type: 'object',
    required: [
      'schema',
      'certificationSchema',
      'valid',
      'protocol',
      'summary',
      'failures',
      'artifacts',
      'limitations',
      'reportDigest',
    ],
    properties: {
      schema: { const: 'polytwist.ideal-rigid-display-experiment.v1' },
      certificationSchema: { const: 'polytwist.ideal-rigid-display-certificate.v1' },
      valid: { type: 'boolean' },
      protocol: {
        type: 'object',
        required: ['seed', 'stateCount', 'progressSamples', 'artifactIds', 'assertions'],
      },
      summary: {
        type: 'object',
        required: [
          'artifactCount',
          'stateCount',
          'dockedCertificates',
          'legalMoveChecks',
          'blockedMoveObservations',
          'animationCertificates',
          'committedTurnCertificates',
          'inverseRestorations',
        ],
      },
      failures: { type: 'array' },
      artifacts: {
        type: 'array',
        items: {
          type: 'object',
          required: [
            'artifactId',
            'puzzleId',
            'family',
            'geometryHash',
            'sourceExactness',
            'logicalPieces',
            'renderablePieces',
            'bandageCount',
            'scramble',
            'actionCoverage',
            'counts',
            'finalStateFingerprint',
          ],
          properties: {
            geometryHash: { type: 'string', pattern: '^[0-9a-f]{64}$' },
          },
        },
      },
      limitations: { type: 'array', items: { type: 'string' } },
      reportDigest: {
        type: 'string',
        pattern: '^ideal-rigid-display-experiment1-[0-9a-f]{32}$',
      },
    },
  },
  'state-graph': {
    $id: id('state-graph'),
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'Bounded exact state graph',
    type: 'object',
    required: ['schema', 'puzzleId', 'summary', 'nodes'],
    properties: {
      schema: { const: 'kinescope.state-graph.v1' },
      puzzleId: { type: 'string' },
      summary: { type: 'object' },
      nodes: { type: 'array' },
      edges: { type: 'array' },
    },
  },
  'render-request': {
    $id: id('render-request'),
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'Server render request',
    type: 'object',
    required: ['spec'],
    properties: {
      spec: { type: 'object' },
      state: { type: 'object' },
      sequence: { type: 'array', items: { type: 'string' } },
      mode: { enum: ['studio', 'albedo', 'piece', 'face', 'normal', 'depth'] },
      width: { type: 'integer', minimum: 32, maximum: 2048 },
      height: { type: 'integer', minimum: 32, maximum: 2048 },
      camera: { type: 'object' },
    },
  },
});
